add checkEnv if no args provided

diff --git a/bin/annotwg b/bin/annotwg
--- a/bin/annotwg
+++ b/bin/annotwg
@@ -129,7 +129,7 @@ retrieve_annot(){
 
 # if no arguments, display usage
 if (( $# == 0 )) ; then
-    echo "ERROR : No argument provided" >&2 && display_usage && exit 1
+    echo "ERROR : No argument provided" >&2 && checkEnv && display_usage && exit 1
 fi
 
 while (( $# > 0 ))
